# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='შეიქმნა')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='განახლდა')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='პასუხი')),
            ],
            options={
                'verbose_name': 'პასუხი',
                'verbose_name_plural': 'პასუხები',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='შეიქმნა')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='განახლდა')),
                ('question', models.CharField(max_length=200, verbose_name='შეკითხვა')),
            ],
            options={
                'verbose_name': 'შეკითხვა',
                'verbose_name_plural': 'შეკითხვები',
            },
        ),
        migrations.CreateModel(
            name='QuestionMix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='შეიქმნა')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='განახლდა')),
                ('function', models.CharField(choices=[('', 'ფუნქციას არ იძახებს')], default='', max_length=20, verbose_name='გამოსაძახებელი ფუნქცია')),
            ],
            options={
                'verbose_name': 'კითხვა - პასუხი',
                'verbose_name_plural': 'კითხვა - პასუხები',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='mix',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.QuestionMix'),
        ),
        migrations.AddField(
            model_name='answer',
            name='mix',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.QuestionMix'),
        ),
    ]
