# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmix',
            name='function',
            field=models.IntegerField(blank=True, choices=[(0, 'ფუნქციას არ იძახებს')], default=0, max_length=20, verbose_name='გამოსაძახებელი ფუნქცია'),
        ),
    ]
